exclude: 'requirements|docs|node_modules|migrations|.git|.tox|env.example.yaml|.pre-commit-config.yaml|fake_data|LOS.postman_collection.json|main.py'
default_stages: [ commit ]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
      - id: no-commit-to-branch
        args: [ --branch,'develop-deploy' ]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
        args: [ '--settings-file=setup.cfg' ]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        args: ['--config=setup.cfg', '--ignore=W503']
        additional_dependencies: [flake8-isort]
